remote_theme: just-the-docs/just-the-docs
markdown: GFM
#Title
title: DDU
# Enable or disable heading anchors
heading_anchors: false
# External navigation links
nav_external_links:
  - title: Temaer
    url: https://digitaltdesignlyngby.github.io/#temaer
    hide_icon: true
  - title: Projektarbejde
    url: https://digitaltdesignlyngby.github.io/#projektarbejde-i-ddu
    hide_icon: true
  - title: Projekter og forl√∏b
    url: https://digitaltdesignlyngby.github.io/#projekter-og-forlb
    hide_icon: true

###########################

#related_resources_title: Other Resources

#related_resources_list:

#- title: Forums
#  hurl: https://some.developer.forum.com/

#- title: More Documentation
#  hurl: https://more.documentation.company.com

#- title: Documentation Portal
#  hurl: https://my.documentation.portal
